openapi: 3.0.3
info:
  title: Accounting
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: mail@greensight.ru
  version: 1.0.0
  description: Accounting
servers:
  - url: /api/v1
tags:
  - name: examples
    description: Тэг-пример
paths:
  /accounts:
    $ref: './accounts/paths.yaml#/AccountsCreate'
  /accounts/{id}:
    $ref: './accounts/paths.yaml#/AccountsCurrent'
  /accounts:mass-delete:
    $ref: './accounts/paths.yaml#/AccountsMassDelete'
  /accounts:search:
    $ref: './accounts/paths.yaml#/AccountsSearch'

  /nomenclatures:
    $ref: './nomenclatures/paths.yaml#/NomenclaturesCreate'
  /nomenclatures/{id}:
    $ref: './nomenclatures/paths.yaml#/NomenclaturesCurrent'
  /nomenclatures:mass-delete:
    $ref: './nomenclatures/paths.yaml#/NomenclaturesMassDelete'
  /nomenclatures:search:
    $ref: './nomenclatures/paths.yaml#/NomenclaturesSearch'
  /nomenclatures:search-one:
    $ref: './nomenclatures/paths.yaml#/NomenclaturesSearchOne'

  /service-groups:
    $ref: './services/paths.yaml#/ServiceGroupsCreate'
  /service-groups/{id}:
    $ref: './services/paths.yaml#/ServiceGroupsCurrent'
  /service-groups:mass-delete:
    $ref: './services/paths.yaml#/ServiceGroupsMassDelete'
  /service-groups:search:
    $ref: './services/paths.yaml#/ServiceGroupsSearch'
  /service-groups:tree:
    $ref: './services/paths.yaml#/ServiceGroupsTree'

  /services:
    $ref: './services/paths.yaml#/ServicesCreate'
  /services/{id}:
    $ref: './services/paths.yaml#/ServicesCurrent'
  /services:mass-delete:
    $ref: './services/paths.yaml#/ServicesMassDelete'
  /services:search:
    $ref: './services/paths.yaml#/ServicesSearch'
  /services:search-one:
    $ref: './services/paths.yaml#/ServicesSearchOne'

components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  requestBodies:
    MassDeleteBody:
      required: true
      content:
        application/json:
          schema:
            $ref: './common_schemas.yaml#/RequestBodyMassOperation'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
    AccountTypeEnum:
      $ref: './accounts/enums/account_type_enum.yaml'
    ObjectTypeEnum:
      $ref: './nomenclatures/enums/object_type_enum.yaml'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    DeleteResponse:
      description: Удаление выполнено
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EmptyDataResponse'
