#!/bin/bash

export $(sed '/^#/d' .docker/.env)

docker run --rm -it \
    --entrypoint="" \
    --network=${NETWORK} \
    -v$(pwd):/var/www \
    -v${ENSI_ROOT}:/var/project \
    -u$(id -u):$(id -g) \
    ${TOOLS_IMAGE?"TOOLS_IMAGE variable in .docker/.env is required"} \
    php artisan $@
