#!/bin/sh

set -e

export $(sed '/^#/d' .docker/.env)

tag=${1:-"${PHP_TAG?"PHP_TAG variable in .docker/.env is required"}"}
repo=${2:-"${PHP_IMAGE?"PHP_IMAGE variable in .docker/.env is required"}"}

docker build \
  --file .docker/php/Dockerfile \
  -t ${repo}:${tag} \
  .
