#!/bin/bash

# Usage: .docker/make-env [project_dir] [service_name] [project_name] [data_dir]

CURRENT_DIR=$(pwd)
PARENT_DIR=$(dirname $CURRENT_DIR)
PARENT_PARENT_DIR=$(dirname $PARENT_DIR)

PROJECT_DIR=${1:-${PARENT_PARENT_DIR}}
SERVICE_NAME=${2:-$(basename ${CURRENT_DIR})}
PROJECT_NAME=${3:-$(basename ${PROJECT_DIR})}
DATA_DIR=${4:-"${PROJECT_DIR}/data"}

COMPOSER_HOME=${COMPOSER_HOME:-"$HOME/.config/composer"}
COMPOSER_CACHE_DIR=${COMPOSER_CACHE_DIR:-"$HOME/.cache/composer"}

NPM_CACHE_DIR=${NPM_CACHE_DIR:-"$HOME/.npm"}
CONFIG_DIR=${CONFIG_DIR:-"$HOME/.config"}

USER_ID=$(id -u)
GROUP_ID=$(id -g)

sed -e "s!#PROJECT_DIR#!${PROJECT_DIR}!" \
    -e "s!#SERVICE_DIR#!${CURRENT_DIR}!" \
    -e "s!#SERVICE_NAME#!${SERVICE_NAME}!" \
    -e "s!#PROJECT_NAME#!${PROJECT_NAME}!" \
    -e "s!#DATA_DIR#!${DATA_DIR}!" \
    -e "s!#COMPOSER_HOME#!${COMPOSER_HOME}!" \
    -e "s!#COMPOSER_CACHE_DIR#!${COMPOSER_CACHE_DIR}!" \
    -e "s!#NPM_CACHE_DIR#!${NPM_CACHE_DIR}!" \
    -e "s!#CONFIG_DIR#!${CONFIG_DIR}!" \
    -e "s!#USER_ID#!${USER_ID}!" \
    -e "s!#GROUP_ID#!${GROUP_ID}!" \
    .docker/.env.example > .docker/.env
