#!/bin/bash

# Usage: .docker/make-env [service-name] [shared-data-dir]

SRC_DIR=$(pwd)
SERVICE=${1:-$(basename "${SRC_DIR}")}
DOMAIN_DIR=$(dirname "${SRC_DIR}")
ENSI_DIR=$(dirname "${DOMAIN_DIR}")
SHARED_DATA_DIR=${2:-"${ENSI_DIR}/data"}

sed -e "s!#SERVICE#!${SERVICE}!" \
    -e "s!#SRC_DIR#!${SRC_DIR}!" \
    -e "s!#SHARED_DATA_DIR#!${SHARED_DATA_DIR}!" \
    -e "s!#ENSI_ROOT#!${ENSI_DIR}!" \
    .docker/.env.example > .docker/.env
