#!/bin/bash

cd .docker
case "$1" in
    up)
        docker-compose up -d php nginx
        ;;
    down)
        docker-compose down
        ;;
    --)
        shift
        docker-compose $@
        ;;
    *)
        echo -e "Usage: service COMMAND\n\nExamples:\n\tservice up\n\tservice down\n\tservice -- restart php" >&2
        exit 1
        ;;
esac
