<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

namespace App\Http\ApiV1\OpenApiGenerated\Enums;

/**
 * Тип счета и кассы:
 * * 1 - Наличные
 * * 2 - Безналичные
 */
enum AccountTypeEnum: int
{
    /** Наличные */
    case CASH = 1;
    /** Безналичные */
    case NON_CASH = 2;
}
