<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

namespace App\Http\ApiV1\OpenApiGenerated\Enums;

/**
 * Статус документа:
 * * 1 - draft
 * * 2 - fix
 * * 3 - cancel
 */
enum DocumentStatusEnum: int
{
    /** Редактировать */
    case DRAFT = 1;
    /** Зафиксировать */
    case FIX = 2;
    /** Отменить */
    case CANCEL = 3;
}
