<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

namespace App\Http\ApiV1\OpenApiGenerated\Enums;

/**
 * Тип документа:
 * * 201 - Оплата покупателя
 * * 202 - Оплата поставщику
 * * 203 - Внесение средства
 * * 204 - Изъятие средства
 * * 205 - Возврат поставщика
 * * 206 - Возврат покупателю
 * * 207 - Перемещение
 */
enum DocumentFinanceTypeIdEnum: int
{
    /** Покупка */
    case CUSTOMER_PAYMENT = 201;
    /** Продажа */
    case SUPPLIER_PAYMENT = 202;
    /** Оприходование */
    case DEPOSIT = 203;
    /** Списание */
    case WITHDRAWAL = 204;
    /** Возврат от покупателя */
    case REFUND_CUSTOMER = 205;
    /** Возврат от поставщика */
    case REFUND_SUPPLIER = 206;
    /** Перемещение */
    case MOVING = 207;
}
