<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

namespace App\Http\ApiV1\OpenApiGenerated\Enums;

/**
 * Тип документа:
 * * 1 - Покупка
 * * 2 - Продажа
 * * 3 - Оприходование
 * * 4 - Списание
 * * 5 - Возврат от покупателя
 * * 6 - Возврат от поставщика
 * * 7 - Перемещение
 */
enum DocumentStoreTypeIdEnum: int
{
    /** Покупка */
    case PURCHASE = 1;
    /** Продажа */
    case SALE = 2;
    /** Оприходование */
    case RECEIPT = 3;
    /** Списание */
    case WRITE_OFF = 4;
    /** Возврат от покупателя */
    case REFUND_FROM_CUSTOMER = 5;
    /** Возврат от поставщика */
    case REFUND_FROM_SUPPLIER = 6;
    /** Перемещение */
    case MOVING = 7;
}
