<?php

/**
 * NOTE: This file is auto generated by OpenAPI Generator.
 * Do NOT edit it manually. Run `php artisan openapi:generate-server`.
 */

namespace App\Http\ApiV1\OpenApiGenerated\Enums;

/**
 * Тип документа:
 * * 1 - Оплата покупателя
 * * 2 - Оплата поставщику
 * * 3 - Внесение средства
 * * 4 - Изъятие средства
 * * 5 - Возврат поставщика
 * * 6 - Возврат покупателю
 * * 7 - Перемещение
 */
enum DocumentFinanceTypeIdEnum: int
{
    /** Покупка */
    case CUSTOMER_PAYMENT = 1;
    /** Продажа */
    case SUPPLIER_PAYMENT = 2;
    /** Оприходование */
    case DEPOSIT = 3;
    /** Списание */
    case WITHDRAWAL = 4;
    /** Возврат от покупателя */
    case REFUND_CUSTOMER = 5;
    /** Возврат от поставщика */
    case REFUND_SUPPLIER = 6;
    /** Перемещение */
    case MOVING = 7;
}
