ServiceReadonlyProperties:
  type: object
  properties:
    id:
      type: integer
      description: Идентификатор
      example: 274
    created_at:
      description: "Дата создания"
      format: date-time
      type: string
      example: "2021-07-03T11:57:28.000000Z"
    updated_at:
      description: "Дата обновления"
      format: date-time
      type: string
      example: "2021-07-03T11:57:28.000000Z"
  required:
    - id
    - created_at
    - updated_at

ServiceFillableProperties:
  type: object
  properties:
    seller_id:
      type: integer
      example: 331
      description: ID продавца
    name:
      type: string
      example: Test
      description: Название
    service_group_id:
      type: integer
      example: 1
      nullable: true
      description: ID группа
    base_price:
      type: integer
      example: 21500
      description: Цена
    description:
      type: string
      description: Описание
      example: Something for something

ServiceFillableRequiredProperties:
  type: object
  required:
    - name
    - seller_id
    - service_group_id

ServiceInclude:
  type: object
  properties:
    service_group:
      $ref: './service_groups.yaml#/ServiceGroup'


Service:
  allOf:
    - $ref: '#/ServiceReadonlyProperties'
    - $ref: '#/ServiceFillableProperties'
    - $ref: '#/ServiceFillableRequiredProperties'
    - $ref: '#/ServiceInclude'

CreateServiceRequest:
  allOf:
    - $ref: '#/ServiceFillableProperties'
    - $ref: '#/ServiceFillableRequiredProperties'

ReplaceServiceRequest:
  allOf:
    - $ref: '#/ServiceFillableProperties'
    - $ref: '#/ServiceFillableRequiredProperties'

PatchServiceRequest:
  allOf:
    - $ref: '#/ServiceFillableProperties'

ServiceResponse:
  type: object
  properties:
    data:
      $ref: '#/Service'
    meta:
      type: object
  required:
    - data

SearchServicesFilter:
  type: object
  properties:
    id:
      type: integer
      description: Идентификатор(ы)
      example: 3
    seller_id:
      type: integer
      description: Идентификатор(ы) продавцы
      example: 3
    name:
      type: string
      description: Название
      example: 'son'
    name_like:
      type: string
      description: Название
      example: 'son'
    name_llike:
      type: string
      description: Название
      example: 'son'
    name_rlike:
      type: string
      description: Название
      example: 'son'
    service_group_id:
      type: integer
      description: ID группы
      example: true
    description_like:
      type: string
      example: some desc
      description: Описание
    base_price:
      type: integer
      example: 300200
      description: Цена
    created_at_gte:
      type: string
      description: Дата создания от
      format: date-time
      example: '2021-12-20T18:00:10.000000Z'
    created_at_lte:
      type: string
      description: Дата создания до
      format: date-time
      example: '2022-12-20T18:00:10.000000Z'
    updated_at_gte:
      type: string
      format: date-time
      description: Дата обновления от
      example: '2021-07-09T04:25:11.000000Z'
    updated_at_lte:
      type: string
      format: date-time
      description: Дата обновления до
      example: '2021-07-03T11:57:28.000000Z'

SearchServicesRequest:
  type: object
  properties:
    sort:
      $ref: '../../common_schemas.yaml#/RequestBodySort'
      description: |
        'id',
        'created_at',
        'updated_at',
        'seller_id',
        'base_price',
        'name',
    include:
      $ref: '../../common_schemas.yaml#/RequestBodyInclude'
      description: Связи (include) service_group
    pagination:
      $ref: '../../common_schemas.yaml#/RequestBodyPagination'
    filter:
      $ref: '#/SearchServicesFilter'

SearchOneServicesRequest:
  type: object
  properties:
    include:
      $ref: '../../common_schemas.yaml#/RequestBodyInclude'
      description: Связи -
    filter:
      $ref: '#/SearchServicesFilter'

SearchServicesResponse:
  type: object
  properties:
    data:
      type: array
      items:
        $ref: '#/Service'
    meta:
      type: object
      properties:
        pagination:
          $ref: '../../common_schemas.yaml#/ResponseBodyPagination'
  required:
    - data
    - meta

