#!/bin/sh

cd /var/www

if [ ! -e /var/www/storage/ensi ] && [ -e /var/data ]; then
    ln -s /var/data /var/www/storage/ensi
fi

if [ ! -L /var/www/public/storage ] && [ ! -L /var/www/public/ensi-protected-storage ]; then
    if [ -e vendor ]; then
        php artisan storage:link
    fi
fi

exec "$@"
